New custom logger that utilizes pino and the NR enricher
TeamCodeStream/codestream-server pull request #315
Opened 2023-08-09 20:25 UTC by CalvinAllen

2023-08-09 21:19 UTC, bcanzanella requested changes

2023-08-09 21:19 UTC, bcanzanella commented on api_server/package.json
> +		"pino": "^8.15.0",
nit pick to remove the ^

2023-08-09 21:19 UTC, bcanzanella commented on api_server/package.json
> +		"@newrelic/pino-enricher": "^1.1.1",
nit pick to remove the ^

2023-08-09 21:19 UTC, bcanzanella commented on api_server/newrelic.js
> -  distributed_tracing: {
is this enabled by default?

2023-08-09 21:19 UTC, bcanzanella commented on api_server/newrelic.js
> +  app_name: ['api-apm-test-calvin'],
TODO to change back to 'api'

2023-08-09 21:19 UTC, bcanzanella commented on api_server/newrelic.js
> +    enabled: false,
how come this is false?

2023-08-09 21:29 UTC, CalvinAllen commented on api_server/newrelic.js
> -  distributed_tracing: {
It is with the version we're using

2023-08-09 21:29 UTC, CalvinAllen commented on api_server/newrelic.js
> +    enabled: false,
Still playing with this, but that's the newrelic agent log. We can leave that one enabled, assuming it's not part of the overall problem

2023-08-10 14:35 UTC, CalvinAllen commented on api_server/newrelic.js
> +    enabled: false,
@bcanzanella Maybe this is a case where we leave this one enabled, and let the infrastructure agent forward it?

2023-08-10 15:47 UTC, bcanzanella approved these changes

2023-08-10 15:48 UTC, merged